[package]
name = "lsf-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.13.4", features = ["blocking", "query", "cookies", "json", "form"] }
serde_json = "1.0"
serde = { version = "1.0.229", features = ["derive"] }
anyhow = "1.0.104"
quick-xml = { version = "0.41.0", features = ["serialize"] }

[lints.clippy]
# Enable the pedantic group for the project.
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }

# Disable some documentation links I found a bit too much for this project.
doc_markdown = "allow"  # Missing backticks, bare URLs, etc.
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_safety_doc = "allow"
tabs_in_doc_comments = "allow"
